      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

      - name: Build Docker image
        run: |
          docker build -t static-website .

      - name: Tag Docker image
        run: |
          docker tag static-website:latest ${{ secrets.ECR_REPO }}:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REPO }}:latest
